[workspace]
members = [".", "sqlx-crud-macros", "examples/axum", "examples/serenity"]

[package]
name = "sqlx-crud"
version = "0.4.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/treydempsey/sqlx-crud"
documentation = "https://docs.rs/sqlx-crud"
description = "Derive macro for SQLx to implement Create, Read, Update, and Delete (CRUD) methods for you."
license = "MIT"
keywords = ["sqlx", "orm", "crud", "database"]
categories = ["database", "asynchronous", "web-programming"]
authors = ["Trey Dempsey <trey.dempsey@gmail.com>"]

[features]
default = ["runtime-tokio-rustls"]
runtime-actix-native-tls = ["sqlx/runtime-tokio", "sqlx/tls-native-tls"]
runtime-async-std-native-tls = ["sqlx/runtime-async-std", "sqlx/tls-native-tls"]
runtime-tokio-native-tls = ["sqlx/runtime-tokio", "sqlx/tls-native-tls"]
runtime-actix-rustls = ["sqlx/runtime-tokio", "sqlx/tls-rustls"]
runtime-async-std-rustls = ["sqlx/runtime-async-std", "sqlx/tls-rustls"]
runtime-tokio-rustls = ["sqlx/runtime-tokio", "sqlx/tls-rustls"]

[dependencies]
futures = "0.3"
sqlx = { version = "0.8" }
sqlx-crud-macros = { version = "0.4", path = "sqlx-crud-macros" }
thiserror = "1"

[dev-dependencies]
sqlx = { version = "0.8", features = ["runtime-tokio", "tls-rustls", "sqlite"] }
tokio-test = "0"
